name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2 
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Karma
      run: dotnet build Karma/Karma.csproj --configuration Debug --no-restore
      
    - name: Build ServiceTests
      run: dotnet build KarmaService.Tests/KarmaService.Tests.csproj --configuration Debug --no-restore
    
    - name: Run Tests
      run: dotnet test KarmaService.Tests --no-restore --verbosity normal
